version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: spotify-desk-thing
      POSTGRES_DB: spotify-desk-thing
    ports:
      - 5432:5432